### ISSUE TITLE
Dynamic size preset

### ISSUE THREAD

**Issue by tenphi** [tenphi/numl#32]
`size` attribute can work like this:

```html
<nu-block size="h1"></nu-block>
```

```css
nu-block[size="h1"] {
  font-size: var(--nu-h1-font-size);
  line-height: var(--nu-h1-line-height);
  font-weight: var(--nu-h1-font-weight);
}
```

Probably it would be more reasonably to rename `size` attribute to `font` in that case.

In future `size` attribute can be used in Logical Properties and Values spec for block and inline sizing.
